[package]
name = "database"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "1.1", features = ["macros", "sqlx-sqlite", "runtime-tokio-rustls", "sqlx-postgres", "with-chrono"] }