//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "archived")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ytid: String,
    pub viewed_at: Option<DateTime>,
    pub created_by: i64,
    pub created_at: DateTime,
    pub contributors: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::videos::Entity",
        from = "Column::Ytid",
        to = "super::videos::Column::Ytid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Videos,
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
