//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Banned")]
    Banned,
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Viewed")]
    Viewed,
}
